### PR TITLE
Uploader refactoring

### LINKED ISSUE #129: Uploaded diff images are broken in Happo 2.5.0
Likely broken by https://github.com/Galooshi/happo/commit/602f49a7922daab8216cb11bb63a29d4d22b746f

### PR DESCRIPTION
**Pull request by lencioni**
Fixes #129.

### CODE REVIEW

File: lib/happo/uploader.rb [hunk 1]
```diff
@@ -54,23 +54,28 @@ def find_or_build_bucket
...
-      if @s3_bucket_path.nil? || @s3_bucket_path.empty?
-        SecureRandom.uuid
-      else
-        File.join(@s3_bucket_path, SecureRandom.uuid)
+      @directory ||= begin
+        if @s3_bucket_path.nil? || @s3_bucket_path.empty?
+          SecureRandom.uuid
+        else
+          File.join(@s3_bucket_path, SecureRandom.uuid)
+        end
```
Comment (trotzig) [inline lib/happo/uploader.rb]: Good catch. Sorry for the sloppiness.

**Comment by trotzig** [comment]
Thanks!
